

# Permalinks
permalink:        pretty

# Setup
title:            MeetDarryl
tagline:          'Support Darryl through his battle with Cancer'
description:      'Meet Darryl, a loved and respected member of the Cullowhee community, battling Cancer. Support Darryl and his family through this difficult time and follow us for updates on how he is doing. '
url:              https://meetdarryl.info
baseurl:          /

author:
  name:           'Ivan Shires'
  url:            https://ivanshires.info

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
